### ISSUE TITLE
ARSCTemplate

### ISSUE THREAD

**Issue by NazcaLines** [tomken/010_template_for_android#2]
感谢UP主分享ARSCTemplate。

但是我在分析的过程中，感觉你的ARSCTemplate有bug。
ARSCTemplate中并没有定义ResTable_map结构体，所以当解析遇到Bag类型的时候会出现错误的解析。
原本应该紧接着arsc_mapentry结构体出现多个ResTable_map结构体，但是由于没有定义ResTable_map，010eiditor会将其解析成新的arsc_mapentry,从而导致后面的数据解析错误。

**Comment by tomken** [comment]
你有该示例的样本嘛，或是给我一个包含此样本的的APK下载地址也可以，多谢反馈

**Comment by NazcaLines** [comment]
https://github.com/NazcaLines/ARSC
有两份，WrongAtBag就是Issue中提到的Bag解析错误的文件。
另外一份，模板没有办法正确解析。
其实，WrongAtBag是我手中唯一能被模板解析成功的文件= =

**Comment by tomken** [comment]
请试一下，我在本地修改后能正常解析了，原来考虑不周，多谢反馈！ @NazcaLines

**Comment by NazcaLines** [comment]
感谢UP主~
还有就是WrongAtBag还是没能解析正确吧，我觉得。
因为我看了模板里并没有定义ResTable_map结构体。UP主可以看 16号type，那个BAG类型解析出错。

**Comment by tomken** [comment]
好的，我再看看

**Comment by tomken** [comment]
@NazcaLines 再次尝试一下，辛苦！

**Comment by NazcaLines** [comment]
Amazing! 
可以了，感谢UP主！辛苦了
